package org.opentripplanner.updater.trip.gtfs;

import java.util.Objects;
import java.util.Optional;
import org.opentripplanner.core.model.i18n.I18NString;
import org.opentripplanner.core.model.i18n.NonLocalizedString;
import org.opentripplanner.core.model.id.FeedScopedId;
import org.opentripplanner.gtfs.mapping.TransitModeMapper;
import org.opentripplanner.transit.model.basic.TransitMode;
import org.opentripplanner.transit.model.network.Route;
import org.opentripplanner.transit.model.organization.Agency;
import org.opentripplanner.transit.service.TransitService;
import org.opentripplanner.updater.trip.gtfs.model.AddedRoute;
import org.opentripplanner.updater.trip.gtfs.model.TripUpdate;

/**
 * Factory for creating routes based on GTFS real-time trip updates.
 */
class RouteFactory {

  record Result(boolean newRouteCreated, Route route) {}

  private final TransitService transitService;

  public RouteFactory(TransitService transitService) {
    this.transitService = transitService;
  }

  /**
   * Extract a new route from the given trip update, creating one if it doesn't exist.
   */
  Result getOrCreate(TripUpdate update) {
    var optionalRoute = findRoute(update);
    var route = optionalRoute.orElseGet(() -> createRoute(update));
    return new Result(optionalRoute.isEmpty(), route);
  }

  private Route createRoute(TripUpdate update) {
    var tripId = update.tripId();
    // the route in this update doesn't already exist, but the update contains the information so it will be created
    var routeId = update.routeId();
    return routeId
      .map(id -> {
        var builder = Route.of(id);

        var addedRouteExtension = AddedRoute.ofTripDescriptor(update);

        var agency = transitService
          .findAgency(new FeedScopedId(tripId.getFeedId(), addedRouteExtension.agencyId()))
          .orElseGet(() -> fallbackAgency(tripId.getFeedId()));

        builder.withAgency(agency);

        builder.withGtfsType(addedRouteExtension.routeType());
        var mode = TransitModeMapper.mapMode(addedRouteExtension.routeType());
        builder.withMode(mode);

        // Create route name
        var name = Objects.requireNonNullElse(
          addedRouteExtension.routeLongName(),
          tripId.toString()
        );
        builder.withLongName(new NonLocalizedString(name));
        builder.withUrl(addedRouteExtension.routeUrl());
        return builder.build();
      })
      .orElseGet(() -> {
        I18NString longName = NonLocalizedString.ofNullable(tripId.getId());
        return Route.of(tripId)
          .withAgency(fallbackAgency(tripId.getFeedId()))
          // Guess the route type as it doesn't exist yet in the specifications
          // Bus. Used for short- and long-distance bus routes.
          .withGtfsType(3)
          .withMode(TransitMode.BUS)
          // Create route name
          .withLongName(longName)
          .build();
      });
  }

  private Optional<Route> findRoute(TripUpdate tripUpdate) {
    return tripUpdate.routeId().flatMap(id -> Optional.ofNullable(transitService.getRoute(id)));
  }

  /**
   * Create dummy agency for added trips.
   */
  private Agency fallbackAgency(String feedId) {
    return Agency.of(new FeedScopedId(feedId, "autogenerated-gtfs-rt-added-route"))
      .withName("Agency automatically added by GTFS-RT update")
      .withTimezone(transitService.getTimeZone().toString())
      .build();
  }
}
