package org.opentripplanner.street.model.vertex;

import org.opentripplanner.core.model.id.FeedScopedId;

/**
 * A label for a vertex so it can be identified when finding vertices in the graph.
 * <p>
 * This is not just a string in order to conserve memory because many vertices have IDs that
 * have the same prefix.
 */
public sealed interface VertexLabel {
  static VertexLabel string(String label) {
    return new StringLabel(label);
  }

  static VertexLabel osm(long nodeId) {
    return new OsmNodeLabel(nodeId);
  }

  static VertexLabel feedScopedId(FeedScopedId id) {
    return new FeedScopedIdLabel(id);
  }

  /**
   * A vertex label that is based on a string.
   */
  record StringLabel(String value) implements VertexLabel {
    @Override
    public String toString() {
      return value;
    }
  }

  /**
   * A vertex label for an OSM node id.
   */
  record OsmNodeLabel(long nodeId) implements VertexLabel {
    private static final String TEMPLATE = "osm:node:%s";

    @Override
    public String toString() {
      return TEMPLATE.formatted(nodeId);
    }
  }

  /**
   * A vertex label for a subsidiary vertex generated by turn restriction graph
   * application. Must be similar to the parent vertex label so that tests can
   * be written sensibly.
   */
  record SubsidiaryVertexLabel(VertexLabel parent, int counter) implements VertexLabel {
    @Override
    public String toString() {
      return parent.toString() + ":" + counter;
    }
  }

  /**
   * A vertex label for a vertex with an entity. Must be similar to the parent vertex label so that
   * tests can be written sensibly.
   * <p>
   * Used for elevator vertices and split vertices.
   */
  record VertexWithEntityLabel(long nodeId, OsmEntityType osmEntityType, long entityId) implements
    VertexLabel {
    private static final String TEMPLATE = "osm:node:%s:%s:%s";

    @Override
    public String toString() {
      return TEMPLATE.formatted(nodeId, osmEntityType, entityId);
    }
  }

  /**
   * A vertex label that represents a feed-scoped id, like a transit stop.
   */
  record FeedScopedIdLabel(FeedScopedId id) implements VertexLabel {
    @Override
    public String toString() {
      return id.toString();
    }
  }
}
