package org.opentripplanner.transit.service;

import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;
import javax.inject.Inject;
import org.locationtech.jts.geom.Envelope;
import org.opentripplanner.transit.model.basic.WgsCoordinate;
import org.opentripplanner.transit.model.framework.FeedScopedId;
import org.opentripplanner.transit.model.site.FlexLocationGroup;
import org.opentripplanner.transit.model.site.FlexStopLocation;
import org.opentripplanner.transit.model.site.GroupOfStations;
import org.opentripplanner.transit.model.site.MultiModalStation;
import org.opentripplanner.transit.model.site.Station;
import org.opentripplanner.transit.model.site.Stop;
import org.opentripplanner.transit.model.site.StopLocation;
import org.opentripplanner.transit.model.site.StopLocationsGroup;
import org.opentripplanner.util.lang.CollectionsView;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Repository for Stop entities.
 */
public class StopModel implements Serializable {

  private static final Logger LOG = LoggerFactory.getLogger(StopModel.class);

  private final Map<FeedScopedId, Stop> regularStopsById;
  private final Map<FeedScopedId, Station> stationById;
  private final Map<FeedScopedId, MultiModalStation> multiModalStationById;
  private final Map<FeedScopedId, GroupOfStations> groupOfStationsById;
  private final Map<FeedScopedId, FlexStopLocation> flexStopsById;
  private final Map<FeedScopedId, FlexLocationGroup> flexStopGroupsById;

  /** The density center of the graph for determining the initial geographic extent in the client. */
  private final WgsCoordinate stopLocationCenter;

  private transient StopModelIndex index;

  @Inject
  public StopModel() {
    this.regularStopsById = Map.of();
    this.stationById = Map.of();
    this.multiModalStationById = Map.of();
    this.groupOfStationsById = Map.of();
    this.flexStopsById = Map.of();
    this.flexStopGroupsById = Map.of();
    this.stopLocationCenter = null;
    this.index = new StopModelIndex(List.of(), List.of(), List.of(), List.of());
  }

  public StopModel(StopModelBuilder builder) {
    this.regularStopsById = builder.stopsById().asImmutableMap();
    this.stationById = builder.stationsById().asImmutableMap();
    this.multiModalStationById = builder.multiModalStationsById().asImmutableMap();
    this.groupOfStationsById = builder.groupOfStationsById().asImmutableMap();
    this.flexStopsById = builder.flexStopsById().asImmutableMap();
    this.flexStopGroupsById = builder.flexStopGroupsById().asImmutableMap();
    this.stopLocationCenter = builder.calculateTransitCenter();
    reindex();
  }

  public static StopModelBuilder of() {
    return new StopModelBuilder();
  }

  public StopModelBuilder copy() {
    return new StopModelBuilder(this);
  }

  /**
   * Return a regular transit stop if found(not flex stops).
   */
  public Stop getRegularStop(FeedScopedId id) {
    return regularStopsById.get(id);
  }

  /**
   * Return all regular transit stops, not flex stops and flex group of stops.
   */
  public Collection<Stop> listRegularStops() {
    return regularStopsById.values();
  }

  public Collection<Stop> findRegularStops(Envelope envelope) {
    return index.queryStopSpatialIndex(envelope);
  }

  public boolean hasFlexLocations() {
    return !flexStopsById.isEmpty();
  }

  /**
   * Flex locations are generated by GTFS graph builder, but consumed only after the street graph is
   * built
   */
  @Nullable
  public FlexStopLocation getFlexStopById(FeedScopedId id) {
    return flexStopsById.get(id);
  }

  public Collection<FlexStopLocation> getAllFlexLocations() {
    return flexStopsById.values();
  }

  public Collection<FlexLocationGroup> getAllFlexStopGroups() {
    return flexStopGroupsById.values();
  }

  public Collection<FlexStopLocation> queryLocationIndex(Envelope envelope) {
    return index.queryLocationIndex(envelope);
  }

  public StopLocation stopByIndex(int stopIndex) {
    return index.stopByIndex(stopIndex);
  }

  public int stopIndexSize() {
    return index.stopIndexSize();
  }

  public Optional<WgsCoordinate> stopLocationCenter() {
    return Optional.ofNullable(stopLocationCenter);
  }

  /**
   * Return regular transit stop, flex stop or flex group of stops.
   */
  @Nullable
  public StopLocation getStopLocation(FeedScopedId id) {
    return getById(id, regularStopsById, flexStopsById, flexStopGroupsById);
  }

  /**
   * Return all stops including regular transit stops, flex stops and flex group of stops.
   */
  public Collection<StopLocation> listStopLocations() {
    return new CollectionsView<>(
      regularStopsById.values(),
      flexStopsById.values(),
      flexStopGroupsById.values()
    );
  }

  @Nullable
  public Station getStationById(FeedScopedId id) {
    return stationById.get(id);
  }

  public Collection<Station> getStations() {
    return stationById.values();
  }

  @Nullable
  public MultiModalStation getMultiModalStation(FeedScopedId id) {
    return multiModalStationById.get(id);
  }

  public Collection<MultiModalStation> getAllMultiModalStations() {
    return multiModalStationById.values();
  }

  @Nullable
  public MultiModalStation getMultiModalStationForStation(Station station) {
    return index.getMultiModalStationForStation(station);
  }

  public Collection<GroupOfStations> getAllGroupOfStations() {
    return groupOfStationsById.values();
  }

  /**
   * Finds a {@link StopLocationsGroup} by id. Return a station, multimodal station, or group of
   * station.
   */
  @Nullable
  public StopLocationsGroup getStopLocationsGroup(FeedScopedId id) {
    return getById(id, stationById, multiModalStationById, groupOfStationsById);
  }

  /**
   * Returns all {@link StopLocationsGroup}s present, including stations, group of stations and
   * multimodal stations.
   */
  public Collection<StopLocationsGroup> listStopLocationGroups() {
    return new CollectionsView<>(
      stationById.values(),
      multiModalStationById.values(),
      groupOfStationsById.values()
    );
  }

  /**
   * @param id Id of Stop, Station, MultiModalStation or GroupOfStations
   * @return The coordinate for the transit entity
   */
  @Nullable
  public WgsCoordinate getCoordinateById(FeedScopedId id) {
    // GroupOfStations
    GroupOfStations groupOfStations = groupOfStationsById.get(id);
    if (groupOfStations != null) {
      return groupOfStations.getCoordinate();
    }
    // Multimodal station
    MultiModalStation multiModalStation = multiModalStationById.get(id);
    if (multiModalStation != null) {
      return multiModalStation.getCoordinate();
    }
    // Station
    Station station = stationById.get(id);
    if (station != null) {
      return station.getCoordinate();
    }
    // Single stop (regular transit and flex)
    StopLocation stop = getStopLocation(id);
    return stop == null ? null : stop.getCoordinate();
  }

  /**
   * Return all stops associated with the given id. If a Station, a MultiModalStation, or a
   * GroupOfStations matches the id, then all child stops are returned. If the id matches a regular
   * stops, area stop or stop group, then a list with one item is returned.
   * An empty list is if nothing is found.
   */
  public Collection<StopLocation> getStopOrChildStops(FeedScopedId id) {
    StopLocationsGroup stops = getStopLocationsGroup(id);
    if (stops != null) {
      return stops.getChildStops();
    }

    // Single stop (regular transit and flex)
    StopLocation stop = getStopLocation(id);
    return stop == null ? List.of() : List.of(stop);
  }

  /**
   * Call this method after deserializing this class. This will reindex the StopModel.
   */
  public void reindexAfterDeserialization() {
    reindex();
  }

  /**
   * This is public to be able to reindex the StopModel after deserialization. DO NOT call
   * this from other places.
   */
  private void reindex() {
    LOG.info("Index stop model...");
    index =
      new StopModelIndex(
        regularStopsById.values(),
        flexStopsById.values(),
        flexStopGroupsById.values(),
        multiModalStationById.values()
      );
    LOG.info("Index stop model complete.");
  }

  @Nullable
  @SafeVarargs
  private static <V> V getById(FeedScopedId id, Map<FeedScopedId, ? extends V>... maps) {
    for (Map<FeedScopedId, ? extends V> map : maps) {
      V v = map.get(id);
      if (v != null) {
        return v;
      }
    }
    return null;
  }
}
