/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.opentripplanner.api.thrift.definition;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BulkFindNearestEdgesResponse implements org.apache.thrift.TBase<BulkFindNearestEdgesResponse, BulkFindNearestEdgesResponse._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BulkFindNearestEdgesResponse");

  private static final org.apache.thrift.protocol.TField RESULTS_FIELD_DESC = new org.apache.thrift.protocol.TField("results", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField COMPUTE_TIME_MILLIS_FIELD_DESC = new org.apache.thrift.protocol.TField("compute_time_millis", org.apache.thrift.protocol.TType.I64, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BulkFindNearestEdgesResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BulkFindNearestEdgesResponseTupleSchemeFactory());
  }

  private List<org.opentripplanner.api.thrift.definition.NearestEdgesResult> results; // required
  private long compute_time_millis; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESULTS((short)1, "results"),
    COMPUTE_TIME_MILLIS((short)10, "compute_time_millis");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESULTS
          return RESULTS;
        case 10: // COMPUTE_TIME_MILLIS
          return COMPUTE_TIME_MILLIS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __COMPUTE_TIME_MILLIS_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);
  private _Fields optionals[] = {_Fields.COMPUTE_TIME_MILLIS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESULTS, new org.apache.thrift.meta_data.FieldMetaData("results", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "NearestEdgesResult"))));
    tmpMap.put(_Fields.COMPUTE_TIME_MILLIS, new org.apache.thrift.meta_data.FieldMetaData("compute_time_millis", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BulkFindNearestEdgesResponse.class, metaDataMap);
  }

  public BulkFindNearestEdgesResponse() {
  }

  public BulkFindNearestEdgesResponse(
    List<org.opentripplanner.api.thrift.definition.NearestEdgesResult> results)
  {
    this();
    this.results = results;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BulkFindNearestEdgesResponse(BulkFindNearestEdgesResponse other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetResults()) {
      List<org.opentripplanner.api.thrift.definition.NearestEdgesResult> __this__results = new ArrayList<org.opentripplanner.api.thrift.definition.NearestEdgesResult>();
      for (org.opentripplanner.api.thrift.definition.NearestEdgesResult other_element : other.results) {
        __this__results.add(other_element);
      }
      this.results = __this__results;
    }
    this.compute_time_millis = other.compute_time_millis;
  }

  public BulkFindNearestEdgesResponse deepCopy() {
    return new BulkFindNearestEdgesResponse(this);
  }

  @Override
  public void clear() {
    this.results = null;
    setCompute_time_millisIsSet(false);
    this.compute_time_millis = 0;
  }

  public int getResultsSize() {
    return (this.results == null) ? 0 : this.results.size();
  }

  public java.util.Iterator<org.opentripplanner.api.thrift.definition.NearestEdgesResult> getResultsIterator() {
    return (this.results == null) ? null : this.results.iterator();
  }

  public void addToResults(org.opentripplanner.api.thrift.definition.NearestEdgesResult elem) {
    if (this.results == null) {
      this.results = new ArrayList<org.opentripplanner.api.thrift.definition.NearestEdgesResult>();
    }
    this.results.add(elem);
  }

  public List<org.opentripplanner.api.thrift.definition.NearestEdgesResult> getResults() {
    return this.results;
  }

  public void setResults(List<org.opentripplanner.api.thrift.definition.NearestEdgesResult> results) {
    this.results = results;
  }

  public void unsetResults() {
    this.results = null;
  }

  /** Returns true if field results is set (has been assigned a value) and false otherwise */
  public boolean isSetResults() {
    return this.results != null;
  }

  public void setResultsIsSet(boolean value) {
    if (!value) {
      this.results = null;
    }
  }

  public long getCompute_time_millis() {
    return this.compute_time_millis;
  }

  public void setCompute_time_millis(long compute_time_millis) {
    this.compute_time_millis = compute_time_millis;
    setCompute_time_millisIsSet(true);
  }

  public void unsetCompute_time_millis() {
    __isset_bit_vector.clear(__COMPUTE_TIME_MILLIS_ISSET_ID);
  }

  /** Returns true if field compute_time_millis is set (has been assigned a value) and false otherwise */
  public boolean isSetCompute_time_millis() {
    return __isset_bit_vector.get(__COMPUTE_TIME_MILLIS_ISSET_ID);
  }

  public void setCompute_time_millisIsSet(boolean value) {
    __isset_bit_vector.set(__COMPUTE_TIME_MILLIS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESULTS:
      if (value == null) {
        unsetResults();
      } else {
        setResults((List<org.opentripplanner.api.thrift.definition.NearestEdgesResult>)value);
      }
      break;

    case COMPUTE_TIME_MILLIS:
      if (value == null) {
        unsetCompute_time_millis();
      } else {
        setCompute_time_millis((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESULTS:
      return getResults();

    case COMPUTE_TIME_MILLIS:
      return Long.valueOf(getCompute_time_millis());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESULTS:
      return isSetResults();
    case COMPUTE_TIME_MILLIS:
      return isSetCompute_time_millis();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BulkFindNearestEdgesResponse)
      return this.equals((BulkFindNearestEdgesResponse)that);
    return false;
  }

  public boolean equals(BulkFindNearestEdgesResponse that) {
    if (that == null)
      return false;

    boolean this_present_results = true && this.isSetResults();
    boolean that_present_results = true && that.isSetResults();
    if (this_present_results || that_present_results) {
      if (!(this_present_results && that_present_results))
        return false;
      if (!this.results.equals(that.results))
        return false;
    }

    boolean this_present_compute_time_millis = true && this.isSetCompute_time_millis();
    boolean that_present_compute_time_millis = true && that.isSetCompute_time_millis();
    if (this_present_compute_time_millis || that_present_compute_time_millis) {
      if (!(this_present_compute_time_millis && that_present_compute_time_millis))
        return false;
      if (this.compute_time_millis != that.compute_time_millis)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(BulkFindNearestEdgesResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    BulkFindNearestEdgesResponse typedOther = (BulkFindNearestEdgesResponse)other;

    lastComparison = Boolean.valueOf(isSetResults()).compareTo(typedOther.isSetResults());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResults()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.results, typedOther.results);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCompute_time_millis()).compareTo(typedOther.isSetCompute_time_millis());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCompute_time_millis()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.compute_time_millis, typedOther.compute_time_millis);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BulkFindNearestEdgesResponse(");
    boolean first = true;

    sb.append("results:");
    if (this.results == null) {
      sb.append("null");
    } else {
      sb.append(this.results);
    }
    first = false;
    if (isSetCompute_time_millis()) {
      if (!first) sb.append(", ");
      sb.append("compute_time_millis:");
      sb.append(this.compute_time_millis);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetResults()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'results' is unset! Struct:" + toString());
    }

  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BulkFindNearestEdgesResponseStandardSchemeFactory implements SchemeFactory {
    public BulkFindNearestEdgesResponseStandardScheme getScheme() {
      return new BulkFindNearestEdgesResponseStandardScheme();
    }
  }

  private static class BulkFindNearestEdgesResponseStandardScheme extends StandardScheme<BulkFindNearestEdgesResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BulkFindNearestEdgesResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESULTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list40 = iprot.readListBegin();
                struct.results = new ArrayList<org.opentripplanner.api.thrift.definition.NearestEdgesResult>(_list40.size);
                for (int _i41 = 0; _i41 < _list40.size; ++_i41)
                {
                  org.opentripplanner.api.thrift.definition.NearestEdgesResult _elem42; // required
                  _elem42 = new org.opentripplanner.api.thrift.definition.NearestEdgesResult();
                  _elem42.read(iprot);
                  struct.results.add(_elem42);
                }
                iprot.readListEnd();
              }
              struct.setResultsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // COMPUTE_TIME_MILLIS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.compute_time_millis = iprot.readI64();
              struct.setCompute_time_millisIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BulkFindNearestEdgesResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.results != null) {
        oprot.writeFieldBegin(RESULTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.results.size()));
          for (org.opentripplanner.api.thrift.definition.NearestEdgesResult _iter43 : struct.results)
          {
            _iter43.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.isSetCompute_time_millis()) {
        oprot.writeFieldBegin(COMPUTE_TIME_MILLIS_FIELD_DESC);
        oprot.writeI64(struct.compute_time_millis);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BulkFindNearestEdgesResponseTupleSchemeFactory implements SchemeFactory {
    public BulkFindNearestEdgesResponseTupleScheme getScheme() {
      return new BulkFindNearestEdgesResponseTupleScheme();
    }
  }

  private static class BulkFindNearestEdgesResponseTupleScheme extends TupleScheme<BulkFindNearestEdgesResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BulkFindNearestEdgesResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.results.size());
        for (org.opentripplanner.api.thrift.definition.NearestEdgesResult _iter44 : struct.results)
        {
          _iter44.write(oprot);
        }
      }
      BitSet optionals = new BitSet();
      if (struct.isSetCompute_time_millis()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetCompute_time_millis()) {
        oprot.writeI64(struct.compute_time_millis);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BulkFindNearestEdgesResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list45 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.results = new ArrayList<org.opentripplanner.api.thrift.definition.NearestEdgesResult>(_list45.size);
        for (int _i46 = 0; _i46 < _list45.size; ++_i46)
        {
          org.opentripplanner.api.thrift.definition.NearestEdgesResult _elem47; // required
          _elem47 = new org.opentripplanner.api.thrift.definition.NearestEdgesResult();
          _elem47.read(iprot);
          struct.results.add(_elem47);
        }
      }
      struct.setResultsIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.compute_time_millis = iprot.readI64();
        struct.setCompute_time_millisIsSet(true);
      }
    }
  }

}

