/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.opentripplanner.api.thrift.definition;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FindPathsRequest implements org.apache.thrift.TBase<FindPathsRequest, FindPathsRequest._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FindPathsRequest");

  private static final org.apache.thrift.protocol.TField TRIP_FIELD_DESC = new org.apache.thrift.protocol.TField("trip", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField OPTIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("options", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FindPathsRequestStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FindPathsRequestTupleSchemeFactory());
  }

  private org.opentripplanner.api.thrift.definition.TripParameters trip; // required
  private org.opentripplanner.api.thrift.definition.PathOptions options; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TRIP((short)1, "trip"),
    OPTIONS((short)2, "options");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TRIP
          return TRIP;
        case 2: // OPTIONS
          return OPTIONS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TRIP, new org.apache.thrift.meta_data.FieldMetaData("trip", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "TripParameters")));
    tmpMap.put(_Fields.OPTIONS, new org.apache.thrift.meta_data.FieldMetaData("options", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "PathOptions")));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FindPathsRequest.class, metaDataMap);
  }

  public FindPathsRequest() {
  }

  public FindPathsRequest(
    org.opentripplanner.api.thrift.definition.TripParameters trip,
    org.opentripplanner.api.thrift.definition.PathOptions options)
  {
    this();
    this.trip = trip;
    this.options = options;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FindPathsRequest(FindPathsRequest other) {
    if (other.isSetTrip()) {
      this.trip = other.trip;
    }
    if (other.isSetOptions()) {
      this.options = other.options;
    }
  }

  public FindPathsRequest deepCopy() {
    return new FindPathsRequest(this);
  }

  @Override
  public void clear() {
    this.trip = null;
    this.options = null;
  }

  public org.opentripplanner.api.thrift.definition.TripParameters getTrip() {
    return this.trip;
  }

  public void setTrip(org.opentripplanner.api.thrift.definition.TripParameters trip) {
    this.trip = trip;
  }

  public void unsetTrip() {
    this.trip = null;
  }

  /** Returns true if field trip is set (has been assigned a value) and false otherwise */
  public boolean isSetTrip() {
    return this.trip != null;
  }

  public void setTripIsSet(boolean value) {
    if (!value) {
      this.trip = null;
    }
  }

  public org.opentripplanner.api.thrift.definition.PathOptions getOptions() {
    return this.options;
  }

  public void setOptions(org.opentripplanner.api.thrift.definition.PathOptions options) {
    this.options = options;
  }

  public void unsetOptions() {
    this.options = null;
  }

  /** Returns true if field options is set (has been assigned a value) and false otherwise */
  public boolean isSetOptions() {
    return this.options != null;
  }

  public void setOptionsIsSet(boolean value) {
    if (!value) {
      this.options = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TRIP:
      if (value == null) {
        unsetTrip();
      } else {
        setTrip((org.opentripplanner.api.thrift.definition.TripParameters)value);
      }
      break;

    case OPTIONS:
      if (value == null) {
        unsetOptions();
      } else {
        setOptions((org.opentripplanner.api.thrift.definition.PathOptions)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TRIP:
      return getTrip();

    case OPTIONS:
      return getOptions();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TRIP:
      return isSetTrip();
    case OPTIONS:
      return isSetOptions();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FindPathsRequest)
      return this.equals((FindPathsRequest)that);
    return false;
  }

  public boolean equals(FindPathsRequest that) {
    if (that == null)
      return false;

    boolean this_present_trip = true && this.isSetTrip();
    boolean that_present_trip = true && that.isSetTrip();
    if (this_present_trip || that_present_trip) {
      if (!(this_present_trip && that_present_trip))
        return false;
      if (!this.trip.equals(that.trip))
        return false;
    }

    boolean this_present_options = true && this.isSetOptions();
    boolean that_present_options = true && that.isSetOptions();
    if (this_present_options || that_present_options) {
      if (!(this_present_options && that_present_options))
        return false;
      if (!this.options.equals(that.options))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(FindPathsRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    FindPathsRequest typedOther = (FindPathsRequest)other;

    lastComparison = Boolean.valueOf(isSetTrip()).compareTo(typedOther.isSetTrip());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTrip()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.trip, typedOther.trip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOptions()).compareTo(typedOther.isSetOptions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOptions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.options, typedOther.options);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FindPathsRequest(");
    boolean first = true;

    sb.append("trip:");
    if (this.trip == null) {
      sb.append("null");
    } else {
      sb.append(this.trip);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("options:");
    if (this.options == null) {
      sb.append("null");
    } else {
      sb.append(this.options);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetTrip()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'trip' is unset! Struct:" + toString());
    }

    if (!isSetOptions()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'options' is unset! Struct:" + toString());
    }

  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FindPathsRequestStandardSchemeFactory implements SchemeFactory {
    public FindPathsRequestStandardScheme getScheme() {
      return new FindPathsRequestStandardScheme();
    }
  }

  private static class FindPathsRequestStandardScheme extends StandardScheme<FindPathsRequest> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FindPathsRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TRIP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.trip = new org.opentripplanner.api.thrift.definition.TripParameters();
              struct.trip.read(iprot);
              struct.setTripIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OPTIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.options = new org.opentripplanner.api.thrift.definition.PathOptions();
              struct.options.read(iprot);
              struct.setOptionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FindPathsRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.trip != null) {
        oprot.writeFieldBegin(TRIP_FIELD_DESC);
        struct.trip.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.options != null) {
        oprot.writeFieldBegin(OPTIONS_FIELD_DESC);
        struct.options.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FindPathsRequestTupleSchemeFactory implements SchemeFactory {
    public FindPathsRequestTupleScheme getScheme() {
      return new FindPathsRequestTupleScheme();
    }
  }

  private static class FindPathsRequestTupleScheme extends TupleScheme<FindPathsRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FindPathsRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.trip.write(oprot);
      struct.options.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FindPathsRequest struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.trip = new org.opentripplanner.api.thrift.definition.TripParameters();
      struct.trip.read(iprot);
      struct.setTripIsSet(true);
      struct.options = new org.opentripplanner.api.thrift.definition.PathOptions();
      struct.options.read(iprot);
      struct.setOptionsIsSet(true);
    }
  }

}

