/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.opentripplanner.api.thrift.definition;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TripDurationResponse implements org.apache.thrift.TBase<TripDurationResponse, TripDurationResponse._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TripDurationResponse");

  private static final org.apache.thrift.protocol.TField EXPECTED_TRIP_DURATION_FIELD_DESC = new org.apache.thrift.protocol.TField("expected_trip_duration", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TripDurationResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TripDurationResponseTupleSchemeFactory());
  }

  private int expected_trip_duration; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EXPECTED_TRIP_DURATION((short)1, "expected_trip_duration");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EXPECTED_TRIP_DURATION
          return EXPECTED_TRIP_DURATION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __EXPECTED_TRIP_DURATION_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EXPECTED_TRIP_DURATION, new org.apache.thrift.meta_data.FieldMetaData("expected_trip_duration", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TripDurationResponse.class, metaDataMap);
  }

  public TripDurationResponse() {
  }

  public TripDurationResponse(
    int expected_trip_duration)
  {
    this();
    this.expected_trip_duration = expected_trip_duration;
    setExpected_trip_durationIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TripDurationResponse(TripDurationResponse other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.expected_trip_duration = other.expected_trip_duration;
  }

  public TripDurationResponse deepCopy() {
    return new TripDurationResponse(this);
  }

  @Override
  public void clear() {
    setExpected_trip_durationIsSet(false);
    this.expected_trip_duration = 0;
  }

  public int getExpected_trip_duration() {
    return this.expected_trip_duration;
  }

  public void setExpected_trip_duration(int expected_trip_duration) {
    this.expected_trip_duration = expected_trip_duration;
    setExpected_trip_durationIsSet(true);
  }

  public void unsetExpected_trip_duration() {
    __isset_bit_vector.clear(__EXPECTED_TRIP_DURATION_ISSET_ID);
  }

  /** Returns true if field expected_trip_duration is set (has been assigned a value) and false otherwise */
  public boolean isSetExpected_trip_duration() {
    return __isset_bit_vector.get(__EXPECTED_TRIP_DURATION_ISSET_ID);
  }

  public void setExpected_trip_durationIsSet(boolean value) {
    __isset_bit_vector.set(__EXPECTED_TRIP_DURATION_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EXPECTED_TRIP_DURATION:
      if (value == null) {
        unsetExpected_trip_duration();
      } else {
        setExpected_trip_duration((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EXPECTED_TRIP_DURATION:
      return Integer.valueOf(getExpected_trip_duration());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EXPECTED_TRIP_DURATION:
      return isSetExpected_trip_duration();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TripDurationResponse)
      return this.equals((TripDurationResponse)that);
    return false;
  }

  public boolean equals(TripDurationResponse that) {
    if (that == null)
      return false;

    boolean this_present_expected_trip_duration = true;
    boolean that_present_expected_trip_duration = true;
    if (this_present_expected_trip_duration || that_present_expected_trip_duration) {
      if (!(this_present_expected_trip_duration && that_present_expected_trip_duration))
        return false;
      if (this.expected_trip_duration != that.expected_trip_duration)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TripDurationResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TripDurationResponse typedOther = (TripDurationResponse)other;

    lastComparison = Boolean.valueOf(isSetExpected_trip_duration()).compareTo(typedOther.isSetExpected_trip_duration());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpected_trip_duration()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expected_trip_duration, typedOther.expected_trip_duration);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TripDurationResponse(");
    boolean first = true;

    sb.append("expected_trip_duration:");
    sb.append(this.expected_trip_duration);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetExpected_trip_duration()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'expected_trip_duration' is unset! Struct:" + toString());
    }

  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TripDurationResponseStandardSchemeFactory implements SchemeFactory {
    public TripDurationResponseStandardScheme getScheme() {
      return new TripDurationResponseStandardScheme();
    }
  }

  private static class TripDurationResponseStandardScheme extends StandardScheme<TripDurationResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TripDurationResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EXPECTED_TRIP_DURATION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.expected_trip_duration = iprot.readI32();
              struct.setExpected_trip_durationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TripDurationResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(EXPECTED_TRIP_DURATION_FIELD_DESC);
      oprot.writeI32(struct.expected_trip_duration);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TripDurationResponseTupleSchemeFactory implements SchemeFactory {
    public TripDurationResponseTupleScheme getScheme() {
      return new TripDurationResponseTupleScheme();
    }
  }

  private static class TripDurationResponseTupleScheme extends TupleScheme<TripDurationResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TripDurationResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.expected_trip_duration);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TripDurationResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.expected_trip_duration = iprot.readI32();
      struct.setExpected_trip_durationIsSet(true);
    }
  }

}

