name: Deploy

on:
  repository_dispatch:
    types: [trigger_deploy]
  workflow_call: # Called after tests pass on master branch push
    inputs:
      environment:
        description: 'Environment (dev or prod)'
        type: string # environment type not supported here, yet
        default: dev
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true
        default: dev

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || inputs.environment }}
    concurrency: ${{ github.event.inputs.environment || inputs.environment }}

    env:
      SETTINGS_PATH: ${{ github.workspace }}/OTP/mbta/ci-maven-settings.xml
    
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/OTP

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          settings-path: ${{ github.workspace }}/OTP/mbta
      
      - uses: actions/checkout@v2
        with:
          repository: mbta/onebusaway-gtfs-modules
          path: ${{ github.workspace }}/onebusaway-gtfs-modules
          fetch-depth: 1

      - name: Install onebusaway-gtfs-modules
        run: |
          mvn clean install -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dlicense.skip=true -s $SETTINGS_PATH
        working-directory: ${{ github.workspace }}/onebusaway-gtfs-modules

      - name: Update PBF
        run: ./mbta/update_pbf.sh
        working-directory: ${{ github.workspace }}/OTP

      - name: Update GTFS
        run: ./mbta/update_gtfs.sh
        working-directory: ${{ github.workspace }}/OTP

      - name: Build
        working-directory: ${{ github.workspace }}/OTP
        run: |
          mvn clean install -U -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true -s $SETTINGS_PATH
          cp ./target/otp-1.4.0-SNAPSHOT-shaded.jar .
          java -Xmx8G -jar otp-1.4.0-SNAPSHOT-shaded.jar --build var/graphs/mbta/ --basePath var/

      - name: Make deploy
        working-directory: ${{ github.workspace }}/OTP
        run: ./mbta/make_deploy.sh

      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Show file tree
        run: find -maxdepth 2
      
      - name: Deploy
        env:
          AWS_REGION: us-east-1
          EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
          EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: ./mbta/semaphore/deploy.sh
        working-directory: ${{ github.workspace }}/OTP
      
      - uses: mbta/actions/notify-slack-deploy@v1
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
