# Deploy to otp-local on merge or push into master
name: "Update otp-local"

on:
  push:
    branches: [master]

jobs:
  auto:
    name: Deploy ${{ github.ref }} to otp-local
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mbta/actions/build-push-ecr@v1
        id: build-push
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker-repo: ${{ secrets.DOCKER_REPO }}

      - uses: mbta/actions/deploy-ecs@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ecs-cluster: open-trip-planner
          ecs-service: open-trip-planner-local
          docker-tag: ${{ steps.build-push.outputs.docker-tag }}
          requires-secrets: 'false'
      
      - uses: mbta/actions/notify-slack-deploy@v1
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
