name: Deploy to ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment # will be prod, dev or dev-green
        required: true
        default: dev-green

concurrency:
  group: deploy-${{ github.event.inputs.environment }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.inputs.environment != 'prod' }}
    name: Deploy ${{ github.ref }} to ${{ github.event.inputs.environment }}
    environment:
      name: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: mbta/actions/build-push-ecr@v1
        id: build-push
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          docker-repo: ${{ secrets.DOCKER_REPO }}

      - uses: mbta/actions/deploy-ecs@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ecs-cluster: open-trip-planner
          ecs-service: format('open-trip-planner-{0}', github.event.inputs.environment)
          docker-tag: ${{ steps.build-push.outputs.docker-tag }}
          requires-secrets: 'false'
      
      - uses: mbta/actions/notify-slack-deploy@v1
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
