name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment # will be prod, dev, dev-green or dev-blue
        required: true
        default: dev-green

jobs:
  deploy:
    name: Deploy ${{ github.ref_name }} to OTP-${{ github.event.inputs.environment }}
    uses: ./.github/workflows/use-deploy-ecs.yml
    with:
      deployment-env: ${{ github.event.inputs.environment }}
    secrets: inherit
